import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "on-primary-fixed-variant": "#00419e",
        "on-tertiary-fixed": "#191c1e",
        "outline-variant": "#c3c6d5",
        "error-container": "#ffdad6",
        surface: "#faf8ff",
        "surface-tint": "#2559bd",
        "on-tertiary-container": "#bcbfc1",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-background": "#131b2e",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-fixed-variant": "#444749",
        "primary-container": "#0047ab",
        "on-primary-fixed": "#001946",
        "surface-container-low": "#f2f3ff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-surface": "#131b2e",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#fffbff",
        outline: "#737784",
        background: "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "tertiary-container": "#4b4e50",
        error: "#ba1a1a",
        "tertiary-fixed": "#e0e3e5",
        secondary: "#712ae2",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        "on-surface-variant": "#434653",
        "secondary-container": "#8a4cfc",
        "surface-dim": "#d2d9f4",
        primary: "#00327d",
        tertiary: "#343739",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        "inverse-primary": "#b1c5ff",
        "on-primary-container": "#a5bdff",
        "primary-fixed-dim": "#b1c5ff",
        "secondary-fixed": "#eaddff",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        unit: "8px",
        "container-max": "1280px",
        "section-padding": "80px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg": ["Montserrat", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": [
          "12px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
